Add user apis
toyokumo/kintone-clj pull request #16
Opened 2019-12-17 05:47 UTC by egs33

Add support for User API

- [Get Users](https://developer.kintone.io/hc/en-us/articles/115008421668)
- [Get Department's Users](https://developer.kintone.io/hc/en-us/articles/115008421508)
- [Get Group's Users](https://developer.kintone.io/hc/en-us/articles/115008271687)
- [Add Users](https://developer.kintone.io/hc/en-us/articles/115001864014)
- [Update Users](https://developer.kintone.io/hc/en-us/articles/115001865774)
- [Update User Codes](https://developer.kintone.io/hc/en-us/articles/115001865593)
- [Update User Services](https://developer.kintone.io/hc/en-us/articles/115001865693)
- [Delete Users](https://developer.kintone.io/hc/en-us/articles/115001865533)
- [Get Departments](https://developer.kintone.io/hc/en-us/articles/115008271847)
- [Get User's Departments](https://developer.kintone.io/hc/en-us/articles/115008271807)
- [Add Departments](https://developer.kintone.io/hc/en-us/articles/360000286061)
- [Update Departments](https://developer.kintone.io/hc/en-us/articles/360000286601)
- [Update Department Codes](https://developer.kintone.io/hc/en-us/articles/360000286621)
- [Delete Departments](https://developer.kintone.io/hc/en-us/articles/360000287922)
- [Get Groups](https://developer.kintone.io/hc/en-us/articles/115008421608)
- [Get User's Groups](https://developer.kintone.io/hc/en-us/articles/115008271787)

2020-01-07 00:35 UTC, makinoshi requested changes
I want you to add `get-all-users`, `get-all-organizations`, `get-all-groups`, `get-all-organization-users` and `get-all-group-users` like `get-all-records`.

2020-01-07 00:35 UTC, makinoshi commented on src/kintone_client/user.cljc
> +  "Gets information of users.
I'd like you to write that this API can't use with API token.

2020-01-07 00:35 UTC, makinoshi commented on src/kintone_client/user.cljc
> +    [] :currentCode - The current User Code (log-in name).
I like
```
- sequence of map
  A map includes these keys
    :curentCode - The ...
```
instead of the way `[] :kw`.

2020-01-07 00:35 UTC, makinoshi commented on src/kintone_client/user.cljc
> +(defn update-org-codes
I like `update-organization-codes`. I think it to be redundant but the priority of the name unity is more important.

2020-01-07 00:35 UTC, makinoshi commented on src/kintone_client/user.cljc
> +  "Gets information of Users that belong to a organization, including their Job title.
I prefer `Gets information of users that belong to the organization. Each of userTitles may have "title" of the job`.

2020-06-29 02:36 UTC, saitouena commented on src/kintone_client/user.cljc
> +  "Gets information of users.
https://github.com/toyokumo/kintone-client/pull/16/commits/e92e0f5fd240f7c42a497e32ddf9544b16e7cef3
resolved with this commit

2020-06-29 03:13 UTC, saitouena commented on src/kintone_client/user.cljc
> +    :else (get-all conn get-users :users)))
I'll add an additional signature like `(get-all-users conn)` later. It just falls back to the 2-arity signature.

2020-06-29 03:13 UTC, saitouena commented on src/kintone_client/user.cljc
> +    :else (get-all conn get-organizations :organizations)))
I'll add an additional signaure.

2020-06-29 03:13 UTC, saitouena commented on src/kintone_client/user.cljc
> +    :else (get-all conn get-groups :groups)))
I'll add an additional signaure.

2020-06-29 03:30 UTC, saitouena commented on dev/test.clj
> +(comment
I don't know why these tests are commented out, but these test will work. I'll check it later.

2020-06-29 03:32 UTC, saitouena approved these changes
It seems good.
I'll cut a release after checking if it works properly.

2020-06-29 03:32 UTC, merged

2020-06-29 03:37 UTC, saitouena commented on dev/test.clj
> +(comment
These are commented out because these tests can cause the deletion of user (by @egs33 )